apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
    advertiseAddress: 192.168.77.1 #这里可以设置network-splite地址
    bindPort: 6443
nodeRegistration:
    kubeletExtraArgs:
        cgroup-driver: "systemd"
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
#imageRepository: registry.aliyuncs.com/google_containers
kubernetesVersion: 1.23.3
networking:
  dnsDomain: cluster.local
  podSubnet: 10.226.0.0/16
  serviceSubnet: 10.96.0.0/12
clusterName: "example-cluster"
controllerManager:
    extraArgs:
        horizontal-pod-autoscaler-sync-period: "10s"
        node-monitor-grace-period: "10s"
apiServer:
    extraArgs:
        runtime-config: "api/all=true"

